### PR TITLE
Adding design folder and 404 page svgs, pngs, and sketch files

### PR DESCRIPTION
**Pull request by JordanTranchina**
Adding design folder and 404 page svgs, pngs, and sketch files

### CODE REVIEW

**Comment by saadq** [comment]
Nice! Just a couple of things – 

1. To keep things organized, could you make a `404` folder and put all the assets in there (i.e. `design/404/`)? This will make it easier when other things are added to the design folder that aren't related to 404 stuff.
2. (Nit) Could you rename `Design` to `design`?

**Comment by saadq** [comment]
If git is being annoying with case sensitivity for folder names, it's fine to just do 1. and I can fix update the folder name later.

**Comment by JordanTranchina** [comment]
complete! addressed the below.

> Nice! Just a couple of things – 
> 
> 1. To keep things organized, could you make a `404` folder and put all the assets in there (i.e. `design/404/`)? This will make it easier when other things are added to the design folder that aren't related to 404 stuff.
> 2. (Nit) Could you rename `Design` to `design`?

**Comment by saadq** [comment]
Nice job @JordanTranchina, thanks very much! I should (hopefully) be able to work on implementing this tomorrow.

**Pull request merged**
