### PR TITLE
Added project requirements to contributing.md

### PR DESCRIPTION
**Pull request by Esslamb**
Added Requirements to list of topics and added new requirement section just after project overview.

### CODE REVIEW

**Comment by saadq** [comment]
Great work @Esslamb! After looking through the doc again, the note in the [Setting Up](https://github.com/saadq/resumake.io/blob/e97a29132ac0a4449c399db85c54bb3ac341e973/contributing.md#setting-up) section: 

> **Note**: You will need to have LaTeX installed on your machine if you wish to test out the resume generation. You can download it here.

should probably be moved into the requirements as well. Could you do that as well?

**Comment by Esslamb** [comment]
@saadq Yes of course! Updated that now mate. I made the LaTeX bullet point a link as I figured it's not as easy to find as node and npm.

**Comment by saadq** [comment]
I agree, I think that's a good idea as well. But right now it's linking to my `node-latex` module which is just what I use to actually run the `latex` process, it isn't where you would need to download it from. The actual download link should be: https://www.latex-project.org/get/

Once that's fixed I think this is good to go!

**Comment by Esslamb** [comment]
Hey, @saadq this should be all done now. FYI I have a lot of react/js/node/go experience if you ever need additional help :+1:

**Comment by saadq** [comment]
Awesome, would definitely love to have more contributions! I'll be opening some more issues soon for things that need to be fixed/features that need to be added so keep a lookout on those and I can ping you if you'd like when I make them and you can work on them if any interest you.

**Comment by saadq** [comment]
Late, but just wanted to let you know I've updated the README with the latest contributors and have added you. Thanks again for your contribution!

**Pull request merged**
