### PR TITLE
fix: hyperlink: urls in pdf 

### PR DESCRIPTION
**Pull request by ngmgit**
URL's were not clickable due to missing href latex package import and tags.

### CODE REVIEW

**Comment by ngmgit** [comment]
I made the changes for other templates, but couldnt figure out why the templates 4 and 7 dont work with these changes.

**Comment by ducaale** [comment]
Thanks @ngmgit.

Do you have an example of an unclickable link? I'm trying to reproduce the issue you saw locally.

**Comment by ngmgit** [comment]
https://github.com/saadq/resumake.io/assets/10939602/e8e36cc8-a15d-4a35-8239-0a4c90cdb93b

@ducaale 
Added a project and its url but when I generate the pdf the link is not clickable, please check the video.

**Review by ducaale — APPROVED** [review]
Looks good. We can address the template 4 & 7 project links in a follow-up PR.

**Pull request merged**
