### PR TITLE
Issue/templates

### PR DESCRIPTION
**Pull request by alokpant**
Based on issue: https://github.com/saadq/resumake.io/issues/56

PR contains two templates:
- [x] Issue Template
- [x] Feature/Enhancement Request Template

Proposed Solution:
screen shot 2018-05-24 at 21 32 33

When user click on 'New Issue' on issue, they will have option to choose either of options or select a general one.

Steps to enable it:
- Go to Settings
- Under Issues, there will be now new option to select templates
- Click 'Add a template' dropdown and select Issue and Featured Templates
- Merge PR

### CODE REVIEW

**Comment by saadq** [comment]
Woah, I didn't even know this was possible – must be a new feature. I had originally just meant to put both templates in one page, and the user can remove the info that isn't relevant, but this is way better. Great work @alokpant! I'll be able to look at the actual contents later today or tomorrow, but this is looking really nice :)

**Comment by saadq** [comment]
Merged, thanks a lot @alokpant! :)

I've added you as a contributor in the README.

**Comment by alokpant** [comment]
@saadq Thank you very much. I will try to pick up more issues.

**Comment by alokpant** [comment]
@saadq I saw that issue template is not loaded. I wanted to change it manually but it do not have privilege.

**Comment by saadq** [comment]
Will look into this when I get home...

**Comment by saadq** [comment]
Sorry kind of got preoccupied with life :|

Going to reopen this until I figure out what's wrong

**Pull request merged**
