### PR TITLE
added Docker/Docker-compose support and added setting up for docker t…

### PR DESCRIPTION
**Pull request by m-bal**
I added support for docker and docker-compose let me know what you think of the changes and let me know if I am doing anything wrong since this is my first time contributing to an open source project. I think I can add more information in the `contribute.md` file for docker and docker-compose for those who are not familiar with docker and docker-compose. 

Thank you so much for creating a wonderful website.

### CODE REVIEW

**Comment by saadq** [comment]
Thanks so much for the PR @m-bal :)! 

I'll be checking this out in the weekend and may have some questions when I test it out since I'm a bit of a Docker newb

**Comment by saadq** [comment]
Sorry, I ended up finishing moving into a new place so didn't have time. Will def try this out tomorrow!

**Comment by saadq** [comment]
Hey, so I just tested out your changes, and running `docker-compose up -d` in the `app` folder worked perfectly for me. I'm a bit confused as to how to proceed after that though. I do see the app show up in the Docker desktop app:

Screen Shot 2020-10-05 at 10 54 08 PM

But when I click on the start button, it just stops immediately with a message that says "EXITED (UNDEFINED)" as you can see above. I've also tried running stuff like `docker run app` or `docker start app` etc, but doesn't seem to work.

As mentioned, I'm a Docker noob so I'm probably doing something obviously stupid, so any tips would be appreciated 😅

After I'm able to verify this, I can merge in this awesome PR :D

**Comment by m-bal** [comment]
Hey,

Try running without the `-d` flag and so with just `docker-compose up`.  Without the flag you'll be able to see the output from both the server and client container simultaneously.

**Comment by saadq** [comment]
output of running that command is below. Seems to be missing dependency issue. just for clarity, the only other command i've run is `docker-compose -d` before this. Should that have been enough to install the deps or do I still need to do `npm install` beforehand?

```
λ app → docker-compose up
Starting app_server_1 ... done
Starting app_client_1 ... done
Attaching to app_server_1, app_client_1
server_1  |
server_1  | > resumake-server@1.0.0 start /home/node/app/server
server_1  | > nodemon --watch 'src/**/*.ts' --exec ts-node src/index.ts
server_1  |
server_1  | sh: nodemon: not found
server_1  | npm ERR! code ELIFECYCLE
server_1  | npm ERR! syscall spawn
server_1  | npm ERR! file sh
server_1  | npm ERR! errno ENOENT
server_1  | npm ERR! resumake-server@1.0.0 start: `nodemon --watch 'src/**/*.ts' --exec ts-node src/index.ts`
server_1  | npm ERR! spawn ENOENT
server_1  | npm ERR!
server_1  | npm ERR! Failed at the resumake-server@1.0.0 start script.
server_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
server_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
server_1  |
server_1  | npm ERR! A complete log of this run can be found in:
server_1  | npm ERR!     /home/node/.npm/_logs/2020-10-06T06_32_54_603Z-debug.log
server_1  | app_server_1 exited with code 1
client_1  |
client_1  | > client@3.0.0 start /home/node/app/client
client_1  | > cross-env PORT=4000 react-app-rewired start
client_1  |
client_1  | sh: cross-env: not found
client_1  | npm ERR! code ELIFECYCLE
client_1  | npm ERR! syscall spawn
client_1  | npm ERR! file sh
client_1  | npm ERR! errno ENOENT
client_1  | npm ERR! client@3.0.0 start: `cross-env PORT=4000 react-app-rewired start`
client_1  | npm ERR! spawn ENOENT
client_1  | npm ERR!
client_1  | npm ERR! Failed at the client@3.0.0 start script.
client_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
client_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
client_1  |
client_1  | npm ERR! A complete log of this run can be found in:
client_1  | npm ERR!     /home/node/.npm/_logs/2020-10-06T06_32_54_926Z-debug.log
client_1  | app_client_1 exited with code 1
```

**Comment by m-bal** [comment]
Hey @saadq,

Sorry for not working on this last night but I managed to fix the error the problem was with node_modules being overridden in the container. How should I proceed do you want me to do another pull request or commit the changes to this one?

**Comment by saadq** [comment]
Hey man, definitely don't apologize for not working on it – I appreciate the fact that you're contributing to the project in your spare time so definitely no pressure in that regard :)

And yeah feel free to just commit to your fork and the PR should automatically update. When we want to merge, the commits will be squashed into one.

**Comment by m-bal** [comment]
Okay looks good I tried it on 2 different computers and it works.

**Comment by saadq** [comment]
Works as well from my end. Great job, and thanks a lot for dockerizing this @m-bal! Really appreciate it

**Pull request merged**
